version: '3.7'
services:
  discord-bot:
    container_name: discord-bot
    entrypoint:
      - npm
    command:
      - run
      - start
    build: .
    volumes:
      - ./:/app
      - /app/node_modules